### ISSUE TITLE
How to set a variable?

### ISSUE THREAD

**Issue by aggsol** [GrossoMoreira/shpp#2]
Something like
```
>var result = count 1 3
>vec_sum result

```

**Comment by GrossoMoreira** [comment]
Hi! Sorry for the late reply.

No, shpp does not allow you to do that. shpp is very simple and only allows you to read/write **variables in your code** and call functions. Thus, you cannot instantiate variables in your script; you can only use the variables that you have declared in your code, as shown in the examples in the README file.

It seems that you are looking for a javascript interpreter. For C++, I recommend that you check https://github.com/vgvassilev/cling

**Comment by aggsol** [comment]
I won't a full fledghed language. I just added a store and load functions which works equally good in my case.
