### ISSUE TITLE
Compilation error on Ubuntu14.04

### ISSUE THREAD

**Issue by aggsol** [GrossoMoreira/shpp#3]
```
g++ -std=c++11 -Wl,-rpath=/home/ubuntu/workspace/shpp/bin -Iinclude -Ijsoncons/src example/main.cpp -o bin/example -Lbin  -lreadline -lshpp
bin/libshpp.so: undefined reference to `rl_completion_matches'
bin/libshpp.so: undefined reference to `rl_attempted_completion_function'
bin/libshpp.so: undefined reference to `readline'
bin/libshpp.so: undefined reference to `add_history'
collect2: error: ld returned 1 exit status
make: *** [bin/example] Error 1
```

**Comment by GrossoMoreira** [comment]
Hello again,

I'm afraid I can't help you with this one. Clearly the linker was able to find libreadline.so, however couldn't find the symbols in it. The only thing that comes to mind is that I have included the readline headers without declaring C linkage, and the compiler might be mangling the symbol names. But it works on every machine I've tried so far (Debians and openSUSEs, not Ubuntus but gcc should be the same)..

If you end up solving this issue please share your solution. Thank you!

**Comment by aggsol** [comment]
I added `-lreadline` to the example recipe then it worked like a charm.
